name: build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10","3.11"]
        qt-lib: [pyqt6, pyside6]
        os: [windows-latest, macos-latest]
        include:
          - python-version: "3.10"
            tox-env: "py310"
          - python-version: "3.11"
            tox-env: "py311"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      shell: bash
    - name: Test with pytest
      run: |
        python -m pytest



